### ISSUE TITLE
Switching back and forth between game modes causes crash

### ISSUE THREAD

**Issue by pirates1010** [ZodiacZubeda/gravity-ballz#26]

**Comment by pirates1010** [comment]
FPSLogger: fps: 61
Exception in thread "LWJGL Application" java.lang.NullPointerException
0 is the size before removal
0 is the size before removal
0
	at com.bradvok.gravityballz.screens.GameScreen.create(GameScreen.java:113)
	at com.bradvok.gravityballz.managers.ScreenManager.showScreen(ScreenManager.java:34)
	at com.bradvok.gravityballz.screens.GameChoiceScreen$2.changed(GameChoiceScreen.java:35)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by ZodiacZubeda** [comment]
I am able to switch between game modes without any errors.
