### ISSUE TITLE
NPE when you play through levels and beat manual then try to play maze

### ISSUE THREAD

**Issue by pirates1010** [ZodiacZubeda/gravity-ballz#33]
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.bradvok.gravityballz.screens.GameScreen.create(GameScreen.java:138)
	at com.bradvok.gravityballz.screens.transitions.Transition.create(Transition.java:27)
	at com.bradvok.gravityballz.screens.transitions.FadeTransition.create(FadeTransition.java:36)
	at com.bradvok.gravityballz.managers.ScreenManager.showScreen(ScreenManager.java:40)
	at com.bradvok.gravityballz.screens.GameChoiceScreen$1.changed(GameChoiceScreen.java:27)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:182)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:147)
	at com.badlogic.gdx.scenes.scene2d.ui.Button.setChecked(Button.java:124)
	at com.badlogic.gdx.scenes.scene2d.ui.Button$1.clicked(Button.java:92)
	at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by ZodiacZubeda** [comment]
Ah hell nah I fixed that shit a day ago
